{{- if eq .Values.database.secret  "appmazing-dev-db-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: appmazing-dev-db-secret
  annotations:
    "helm.sh/resource-policy": "keep"  
data:
  password: {{  "testuser"  | b64enc }}
  user: {{ "testuser" | b64enc }}
  postgresql-password: {{  "appmazing"  | b64enc }}
{{- end }}
